### ISSUE TITLE
Rename Project?

### ISSUE THREAD

**Issue by darcyclarke** [richgilbank/Scratch-JS#33]
The project includes more of a "scratchpad" feel to it and not necessarily specific to ES6 (because of the addition of the different compilers) or a Repl. Suggestions...

**Comment by richgilbank** [comment]
:+1:, I [asked on Twitter](https://twitter.com/richgilbank/status/567444958521872384) if anyone had suggestions for it, but came up empty. Agree about the 'scratchpad'/'scratch' emphasis though. The only things that I've found with related names are http://codecanyon.net/item/html5-scratch-card/8721110 (with a flash fallback!) and https://scratch.mit.edu/, found by @tessalt. I don't think `scratch.js` would conflict with the scratch card thing though (non-OSS), so I'm definitely leaning that way. Anyone following have any suggestions? Any yays/nays on scratch.js? 

I suppose I'm also not super sure on naming it x.js because it's not a usual x.js project (for most, it's just a chrome extension...for now...). 

Making a Firefox version is something I'd love to add to the roadmap, but their dev tools SDK is just not quite up to `scratch` yet. 

All this to say...`/shrug`. Open to any questions/comments/threats here, but for now `scratch.js` is a contender. What say you, good people of the interwebs?
