### ISSUE TITLE
Scratch JS ver. 0.0.20 is not compatible with Chrome ver. 46

### ISSUE THREAD

**Issue by bhevesi** [richgilbank/Scratch-JS#66]
Hi, unfortunately this extension doesn't work in Chrome Version 46.0.2490.71 m. OS: Windows 10
I'm not able to write write code as well as run it.
I would be grateful for Your support. Thx.

**Comment by richgilbank** [comment]
Thanks for letting me know - seems to be fixed by https://github.com/richgilbank/Scratch-JS/commit/e52d0e2277acfd23a5b8bbd24c7fa0839d4f29f1; I'm not sure what would have changed to cause it yet, but simply bumping Babel seems to work. Currently publishing in the Chrome web store, so it should be available in the next hour or so. 
Cheers!

**Comment by bhevesi** [comment]
Dear Rich,

I appreciate Your quick reply and many-many thanks for the solution. It works very well.
I wish You the best!
